### ISSUE TITLE
Author has terrible musical taste

### ISSUE THREAD

**Issue by rogierg** [ChessSpider/cartymode#1]
Let me start by saying that this is an awesome project, thanks @ChessSpider!

Steps to reproduce:
1. Install everything according to documentation
2. Start any of the demo songs
3. Terrible noises, blood shoots out of ears, much panic!

Expected result:
1 and 2 remain the same but 3 should be, at least, enjoyable!

Expect a MR soon with some proper songs! 🤣 (After I get my car to work)

**Comment by ChessSpider** [comment]
wontfix
